In [1]:
import numpy as np
from sklearn.neighbors import KDTree

In [11]:
def scale_invariant_features(points, k=4):
    # Create a KDTree for efficient nearest neighbor search
    kdtree = KDTree(points)

    # Find the k nearest neighbors for each point
    _, indices = kdtree.query(points, k=k+1)  # k+1 to exclude the point itself

    # Calculate pairwise ratios for each point
    ratios = []
    for i in range(len(points)):
        neighbors = points[indices[i, 1:]]  # Exclude the point itself
        distances = np.linalg.norm(neighbors - points[i], axis=1)
        pairwise_ratios = distances / np.min(distances)
        ratios.append(pairwise_ratios)

    return np.array(ratios)

In [12]:
# Example usage:
# Assuming 'points' is your numpy array of points (Nx2 or Nx3)
points = np.array([[0, 0], [1, 1], [3, 3], [4, 2]])
features = scale_invariant_features(points)

print("Scale-invariant features:")
print(features)


Scale-invariant features:
[[1.         3.         3.16227766]
 [1.         2.         2.23606798]
 [1.         2.         3.        ]
 [1.         2.23606798 3.16227766]]
